### ISSUE TITLE
Reload the main menu when you've completed an option tree

### ISSUE THREAD

**Issue by jordan-castelloe** [chicken-sloths/bangazon-cli-sprint2#40]
### Context
When a user has completed an action on the main menu (adding a customer, adding products to an order, etc), it should reload the main menu rather than exiting the program.

### Process
1. I think this will probably go in ``ui.js`` but other than that, knock yourself out

### Expected Result
1. When a user completes a step on the main menu, it should reprint the main menu rather than exiting the cli

**Comment by kenziebottoms** [comment]
#50
